# Generated by Django 5.0.2 on 2024-03-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0005_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='slug',
            field=models.SlugField(blank=True, max_length=225),
        ),
    ]
