# Generated by Django 5.0.2 on 2024-03-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0006_advertisement_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
